FROM avo_base

COPY ./avo /avo
COPY ./avo-dashboards /avo-dashboards
COPY ./avo-menu /avo-menu
COPY ./avo-dynamic_filters /avo-dynamic_filters
COPY ./avo-pro /avo-pro
COPY ./avo-advanced /avo-advanced
COPY ./avo-forms /avo-forms
